import Header from "@/components/Header";
import vazirFont from "@/constants/localfont";
import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${vazirFont.variable} font-sans container xl:max-w-screen-xl`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
